ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; -- 예전 버전으로 만들 수 있게 

CREATE USER TEST_USER IDENTIFIED BY test1234; -- id,pw 지정
 
GRANT RESOURCE, CONNECT TO TEST_USER; -- 계정 만드는 권한

ALTER USER TEST_USER DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
-- 테이블 영역 보여주기

CREATE TABLE TEST_TABLE(
	TEST_NO NUMBER PRIMARY KEY,
	TEST_NAME VARCHAR2(30),
	TEST_PROJECT VARCHAR2(30),
	FINAL_DATE DATE DEFAULT SYSDATE
);

INSERT INTO TEST_TABLE VALUES (1, 'Alice', '신비한 나라의 엘리스',default);
INSERT INTO TEST_TABLE VALUES (2, 'Red Hood', '빨간모자',default);
INSERT INTO TEST_TABLE VALUES (3, 'sheep', '7마리 아기 염1소',default);
INSERT INTO TEST_TABLE VALUES (4, 'Rapungell', '라푼젤',default);

UPDATE TEST_TABLE SET TEST_PROJECT = '7마리 아기염소'
WHERE TEST_NO = 3;

SELECT * FROM TEST_TABLE;

-- 만약 SYS 계정에서 TEST_USER.TEST_TABLE을 조회하려면
-- SELECT * FROM TEST_USER.TEST_TABLE;

SELECT * FROM TEST_USER.TEST_TABLE;

-- TEST_USER 계정이 다른 사용자에게 SELECT 권한을 주지 않았다면, 
-- 다른 계정에서 조회할 수 없음

-- GRANT SELECT ON TEST_TABLE TO 다른계정;

-- 테이블이 존재하는지
-- 계정이 맞는지
-- 권한이 있는지
-- COMMIT을 했는지
-- 4가지를 위주로 참고