CREATE TABLE TB_MEMBER (
   MEMBER_NO CHAR(2) CONSTRAINT MEMBER_NO_PK PRIMARY KEY,    
   MEMBER_ID VARCHAR(30) NOT NULL,
   MEMBER_PW VARCHAR(30) NOT NULL,
   MEMBER_NAME VARCHAR(30) NOT NULL,
   ENROLL_DATE DATE DEFAULT CURRENT_DATE);

CREATE TABLE TB_TODO (
   TODO_NO NUMBER CONSTRAINT TODO_NO_PK PRIMARY KEY,
   TODO_BUY VARCHAR2(30),
   TODO_GO VARCHAR2(30),
   TODO_STUDY VARCHAR2(30),
   TODO_TAKE VARCHAR2(30) NOT NULL,
   TODO_SEE VARCHAR2(30),
   FINAL_DATE DATE DEFAULT CURRENT_DATE,
);

SELECT * FROM TB_MEMBER;
SELECT * FROM TB_TODO;

DROP FROM TB_MEMBER;

COMMENT ON COLUMN TB_TODO.TODO_BUY     IS '구매해야할 물건';
COMMENT ON COLUMN TB_TODO.TODO_GO    IS '가고 싶거나 가야 하는 곳';
COMMENT ON COLUMN TB_TODO.TODO_STUDY   IS '해야하는 공부';
COMMENT ON COLUMN TB_TODO.TODO_TAKE   IS '단비같은 휴식';
COMMENT ON COLUMN TB_TODO.TODO_SEE IS '보러 가야 할 것';

CREATE SEQUENCE MEMBER_NO NOCACHE;
CREATE SEQUENCE TODO_NO NOCACHE;

INSERT INTO TB_MEMBER
VALUES(MEMBER_NO_NO.NEXTVAL, 'user01', 'pass01', '고해준', DEFAULT );
INSERT INTO TB_MEMBER
VALUES(MEMBER_NO_NO.NEXTVAL, 'user02', 'pass02', '백은영', DEFAULT );
INSERT INTO TB_MEMBER
VALUES(MEMBER_NO_NO.NEXTVAL, 'user03', 'pass03', '박주완', DEFAULT );


INSERT INTO TB_TODO 
VALUES(TODO_NO_NO.NEXTVAL,'시나모롤 인형','영화관','JDBC','게임 30분','영화', DEFAULT);
INSERT INTO TB_TODO 
VALUES(TODO_NO_NO.NEXTVAL,'초콜렛 간식','학원','영어','간식 먹기','학원 숙제', DEFAULT);
INSERT INTO TB_TODO 
VALUES(TODO_NO_NO.NEXTVAL,'어바등 소설','서점','한국사','유튜브','HTML', DEFAULT);

COMMIT;