CREATE TABLE TB_MEMBER (
   MEMBER_NO CHAR(2) CONSTRAINT MEMBER_NO_PK PRIMARY KEY,    
   MEMBER_ID VARCHAR2(30) NOT NULL,
   MEMBER_PW VARCHAR2(30) NOT NULL,
   MEMBER_NAME VARCHAR2(30) NOT NULL,
   ENROLL_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE TB_TODO (
   TODO_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- 자동 증가 번호
   TODO_DESC VARCHAR2(255) NOT NULL, -- 할 일 내용
   TODO_STATUS VARCHAR2(30) DEFAULT 'PENDING', -- 할 일 상태 (예: PENDING, COMPLETED)
   FINAL_DATE DATE DEFAULT SYSDATE -- 마감일
);

COMMENT ON COLUMN TB_TODO.TODO_NO    IS '숫자';
COMMENT ON COLUMN TB_TODO.TODO_DESC    IS '해야할 일';
COMMENT ON COLUMN TB_TODO.TODO_STATUS   IS '할 일 상태';
COMMENT ON COLUMN TB_TODO.FINAL_DATE   IS '마감일';

CREATE SEQUENCE MEMBER_NO NOCACHE;
CREATE SEQUENCE TODO_NO NOCACHE;

INSERT INTO TB_MEMBER
VALUES(MEMBER_NO_NO.NEXTVAL, 'user01', 'pass01', '고해준', DEFAULT );
INSERT INTO TB_MEMBER
VALUES(MEMBER_NO_NO.NEXTVAL, 'user02', 'pass02', '백은영', DEFAULT );
INSERT INTO TB_MEMBER
VALUES(MEMBER_NO_NO.NEXTVAL, 'user03', 'pass03', '박주완', DEFAULT );


INSERT INTO TB_TODO 
VALUES(TODO_NO_NO.NEXTVAL,'시나모롤 인형','영화관','JDBC','게임 30분','영화', DEFAULT);
INSERT INTO TB_TODO 
VALUES(TODO_NO_NO.NEXTVAL,'초콜렛 간식','학원','영어','간식 먹기','학원 숙제', DEFAULT);
INSERT INTO TB_TODO 
VALUES(TODO_NO_NO.NEXTVAL,'어바등 소설','서점','한국사','유튜브','HTML', DEFAULT);

COMMIT;